services:
  server:
    build: ./nginx
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpressVolume:/var/www/inception/htdocs/wordpress
    restart: always
    networks:
      - inception

  php-fpm:
    container_name: php-fpm
    build: ./wordpress
    depends_on:
      - mariadb
      - redis
    expose:
      - "9000"
    volumes:
      - wordpressVolume:/var/www/inception/htdocs/wordpress
    restart: always
    networks:
      - inception
    env_file:
      - .env
    environment:
      - redis=true
  mariadb:
    container_name: mariadb
    build: ./mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
  redis : 
    container_name: redis 
    build : ./bonus/redis
    networks:
      - inception

volumes:
  wordpressVolume:
  mariadb_data:

networks:
  inception:
